# Generated by Django 3.0.3 on 2020-03-11 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiosite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wavetype', models.CharField(max_length=15, verbose_name='Wave Type')),
            ],
        ),
    ]
